/*
*這個js中保存了app與js中所有的交互方法
*appFuncs原型中存放了js要調的app方法
*appFuncs對象中存放了app要調的js方法
*/

define(['../config'],function(config){
	var appFuncs=function(){};
	appFuncs.prototype={
		/*
		*傳是否收藏
		*/
		CA:function(){
			try{
				myInterfaceName.collectAction(collectId);
			}catch(err){
				console.error(err);
			}
		},
		/*
		*將版本號傳給app
		*/
		sendVersion:function(version){
			try{
				myInterfaceName.sendVersion(version);
			}catch(err){
				console.error(err);
			}
		},
		/*
		*举报跳转
		*/
		report:function(){
			try{
				myInterfaceName.report();
			}catch(err){
				console.error(err);
			}
		},
		/*
		*进入app赞赏
		*/
		useAppReward:function(toast){
			try{
				myInterfaceName.useAppReward(toast);
			}catch(err){
				console.error(err);
			}
		},
		/*
		*跳转到app下载
		*/
		turntodownload:function(url,originalname,size){
			try{
				myInterfaceName.turntodownload(url,originalname,size);
			}catch(err){
				console.error(err);
			}
		},
		/*
		*跳转到平台信息
		*/
		gotoplat:function(){
			try{
				myInterfaceName.gotoplat();
			}catch(err){
				console.error(err);
			}
		},
		/*
		*js传参数给app
		*发送历史id，文章名称，图片路径，文章类型，以及视屏路径或者附件路径给app
		*/
		sendidtoapp:function(aid,title,imgsrc){
			try{
				myInterfaceName.sendIdToAppa(aid);
				myInterfaceName.sendIdToAppb(title);
				myInterfaceName.sendIdToAppc(imgsrc);
			}catch(err){
				console.error(err);
			}
		},
		/*
		*js传参数给app
		*儅文章為視頻或者課件時需要傳路徑
		*/
		sendUrltoApp:function(url){
			try{
				myInterfaceName.sendIdToAppe(url);
			}catch(err){
				console.error(err);
			}
		},
		/*
		*需要將頁面中所有的圖片傳給app，並將當前點擊的是第幾個圖片傳過去
		*/
		sendSingleImgToApp:function(i,imgStr){
			try{
				myInterfaceName.sendSingleImgToApp(i,imgStr);
			}catch(err){
				console.error(err);
			}
		},
		/*
		*傳所有贊賞過的人的所有頭像
		*/
		sendUserPic:function(headPics){
			try{
				myInterfaceName.sendUserPic(headPics);
			}catch(err){
				console.error(err);
			}
		},
		/*
		*傳給app評論的數量和自已是否評論過
		*/
		sendCommentPara:function(num,commentId){
			try{
				myInterfaceName.sendCommentPara(num,commentId);
			}catch(err){
				console.error(err);
			}
		},
	}
	/*
	*app傳收藏id給js
	*/
	appFuncs.getCollectId=function(id){
		collectId=id;
	}
	/*
	*获取参数信息
	*此為項目啓動依賴方法
	*@explain 所有的接口調用，所有的交互都需要這個方法中傳的數據，故此為項目的啓動方法
	*/
	appFuncs.andoridTojs=function(provice,city,area,u,access,article,p,version){
		if(u!=null&&u!=""&&access!=null&&access!=""&&article!=null&&article!=""&&p!=null&&p!=""){
			proviceId=provice;//省id
			cityId=city;//市id
			areaId=area;//區id
			uid=u;//當前用戶id
			accesstoken=access;//驗證accesstoken
			articleId=article;//文章id
			pid=p;//即為creator，創建文章人的id
			version=version;//傳版本號過來
			return {proviceId:proviceId,cityId:cityId,areaId:areaId,uid:uid,accesstoken:accesstoken,articleId:articleId,pid:pid,version:version}
		}else{
			console.error("app數據未完全正確傳送");
			return undefined
		}
	}
	/*
	*傳用戶頭像
	*/
	appFuncs.sendUserPic=function(pics){
		//alert("sendUserPic");
		myInterfaceName.sendUserPic(pics);
	}

	return appFuncs
})