/*
*--1版本迭代
*迭代老版本的綫上學堂article頁面
*@explain compaticle是兼容的意思
*/
define([],function(){
	var Compaticle=function(){

	}
	Compaticle.prototype={
		//为使赞赏，广告，操作在页面最后所写的方法
		//结构搭建时没有考虑好，后期发现发现问题，非常麻烦
		isscroll:function(){
			$("body").css("height","auto");
			$("body").css("overflow","auto");
			$("html").css("height","auto");
			$("#aewordnum").css("position","static");
			$(".award").css("position","static");
			$(".bottom").css("position","static");
			$("#aewordnum").css("width","100%");
			$(".bottom").css("width","100%");
			if(document.body.style.overflow!="hidden"&&document.body.scroll!="no"&&
				document.body.scrollHeight<=$(window).height())
			{

					$(".promote").css("position","fixed");
					if($(".promote").css("display")=="none"){
						$("body").css("height","100%");
						$("body").css("overflow","hidden");
						$("html").css("height","100%");
						$("#aewordnum").css("position","absolute");
						$(".award").css("position","absolute");
						$("#aewordnum").css("width","90%");
						$(".bottom").css("width","90%");
						$(".bottom").css("position","absolute");
						$(".bottom").css("bottom","10px");
						$("#aewordnum").css("bottom","71px");
						$(".award").css("bottom","110px");
						$(".award").css("left","0");
						$(".award").css("right","0");
					}else{
						if($("body").height()<=$(window).height()){
							$("body").css("height","100%");
							$("body").css("overflow","hidden");
							$("html").css("height","100%");
							$("#aewordnum").css("position","absolute");
							$(".award").css("position","absolute");
							$(".bottom").css("position","absolute");
							$("#aewordnum").css("width","90%");
							$(".bottom").css("width","90%");
							$(".bottom").css("bottom","120px");
							$("#aewordnum").css("bottom","191px");
							$(".award").css("bottom","220px");
							$(".award").css("left","0");
							$(".award").css("right","0");
						}
					}
				}else{
					$("body").css("height","auto");
					$("body").css("overflow","auto");
					$("html").css("height","auto");
					$("#aewordnum").css("position","static");
					$(".award").css("position","static");
					$(".bottom").css("position","static");
					$("#aewordnum").css("width","100%");
					$(".bottom").css("width","100%");
					$(".promote").css("position","absolute");
				}
		}
		
	}
	return Compaticle
})